spring:

  application:
    name: sawadee

  kafka:
    bootstrap-servers: www.google.com:9092   

  flyway:
    #url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    #url: 'jdbc:h2:file:./data/demo;DB_CLOSE_ON_EXIT=FALSE'
    #;DB_CLOSE_ON_EXIT=FALSE
    #;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
    #user: sa
    #password:
    locations: classpath:db/migration
    #schemas: PUBLIC
  h2:
    console:
      enabled: true
  datasource:
    #driverClassName: org.h2.Driver
    #url: jdbc:h2:mem:testdb
    #username: sa
    #password:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:53306/sawadee
    username: sawadee
    password: krub 
#  data:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        #bootstrap-model: default

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          jobStore:
            clusterCheckinInterval: 20000
            misfireThreshold: 60000
            #class: org.quartz.impl.jdbcjobstore.JobStoreTX
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
            #driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate #Postgre specific
          scheduler:
            instanceName: quartz-sawadee
            instanceId: AUTO
          threadPool:
            threadCount: 10
            threadPriority: 5
            class: org.quartz.simpl.SimpleThreadPool
   
server:
  port: 2018

kafka:
  enabled: false
  
org:
  quartz:
    scheduler:
      instanceId: AUTO

    
app:
  test:
    cron: 0 * * * * ?
  camel:
    enable: false
  nats:
    enable: false
    audit-topic: audit
    uri: nats://localhost:4222
